from docx import Document
from docx.shared import Pt, RGBColor, Inches, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

doc = Document()

# ── Page margins ──────────────────────────────────────────────────────────────
for section in doc.sections:
    section.top_margin    = Cm(2.5)
    section.bottom_margin = Cm(2.5)
    section.left_margin   = Cm(2.8)
    section.right_margin  = Cm(2.8)

# ── Styles ────────────────────────────────────────────────────────────────────
normal_style = doc.styles['Normal']
normal_style.font.name = 'Arial'
normal_style.font.size = Pt(11)

# ── Helpers ───────────────────────────────────────────────────────────────────
BLUE   = RGBColor(0x1F, 0x4E, 0x79)
RED    = RGBColor(0x7B, 0x24, 0x1C)
GREEN  = RGBColor(0x1E, 0x84, 0x49)
GREY   = RGBColor(0x44, 0x44, 0x44)
BLACK  = RGBColor(0x00, 0x00, 0x00)

def add_cover_title(text, color=BLUE):
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(text)
    run.bold = True
    run.font.size = Pt(20)
    run.font.color.rgb = color
    run.font.name = 'Arial'

def add_subtitle(text):
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(text)
    run.italic = True
    run.font.size = Pt(12)
    run.font.color.rgb = GREY
    run.font.name = 'Arial'
    p.paragraph_format.space_after = Pt(4)

def add_essay_heading(n, title, color=BLUE):
    doc.add_page_break()
    p = doc.add_paragraph()
    run = p.add_run(f'Essay {n}')
    run.bold = True
    run.font.size = Pt(16)
    run.font.color.rgb = color
    run.font.name = 'Arial'
    p.paragraph_format.space_after = Pt(2)

    p2 = doc.add_paragraph()
    run2 = p2.add_run(title)
    run2.bold = True
    run2.italic = True
    run2.font.size = Pt(13)
    run2.font.color.rgb = GREY
    run2.font.name = 'Arial'
    p2.paragraph_format.space_after = Pt(8)

def add_question_box(q_text):
    p = doc.add_paragraph()
    run = p.add_run('Question: ')
    run.bold = True
    run.font.color.rgb = GREEN
    run.font.name = 'Arial'
    run.font.size = Pt(11)
    run2 = p.add_run(q_text)
    run2.italic = True
    run2.font.color.rgb = GREEN
    run2.font.name = 'Arial'
    run2.font.size = Pt(11)
    pf = p.paragraph_format
    pf.left_indent  = Inches(0.3)
    pf.space_before = Pt(4)
    pf.space_after  = Pt(12)

def add_section_label(label, color=BLUE):
    p = doc.add_paragraph()
    run = p.add_run(label)
    run.bold = True
    run.font.size = Pt(10)
    run.font.color.rgb = color
    run.font.name = 'Arial'
    run.font.all_caps = True
    p.paragraph_format.space_before = Pt(10)
    p.paragraph_format.space_after  = Pt(3)

def add_body(text, italic_runs=None):
    """italic_runs = list of substrings to italicise (titles)"""
    p = doc.add_paragraph()
    p.paragraph_format.space_after  = Pt(10)
    p.paragraph_format.first_line_indent = Inches(0)

    titles = ['Nineteen Eighty-Four', '1984', 'V for Vendetta']
    # Simple approach: split on known italic tokens
    import re
    pattern = '(' + '|'.join(re.escape(t) for t in titles) + ')'
    parts = re.split(pattern, text)
    for part in parts:
        r = p.add_run(part)
        r.font.name = 'Arial'
        r.font.size = Pt(11)
        r.font.color.rgb = BLACK
        if part in titles:
            r.italic = True

def add_divider():
    p = doc.add_paragraph('─' * 60)
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_before = Pt(6)
    p.paragraph_format.space_after  = Pt(6)
    for run in p.runs:
        run.font.color.rgb = GREY
        run.font.size = Pt(9)

# ═════════════════════════════════════════════════════════════════════════════
# ESSAYS DATA
# ═════════════════════════════════════════════════════════════════════════════

essays = [

# ── 1 ─────────────────────────────────────────────────────────────────────────
dict(
n=1, theme='Thematic', color=BLUE,
title='Surveillance and Psychological Control',
question='(Thematic — no set question; suitable for any prompt asking about how each text represents control)',
intro="""When the state controls what citizens see, hear, and ultimately think, freedom becomes an illusion maintained not by bars but by the mind itself. George Orwell's 1949 dystopian novel Nineteen Eighty-Four depicts a regime so perfected in its surveillance that citizens police their own consciousness, making dissent feel not merely dangerous but impossible. James McTeigue's 2005 film V for Vendetta presents a surveillance apparatus that retains fatal weaknesses — cracks through which a masked revolutionary can move unseen. Both composers interrogate how governments exercise control through the colonisation of perception, yet arrive at divergent conclusions: Orwell warns that when surveillance is perfected the individual self is ultimately destroyed, while McTeigue argues that no system of control is ever truly complete, and that this incompleteness is where freedom survives.""",
b1_label='The Mechanics of Surveillance: Manufacturing the Self-Policing Citizen',
body1="""Both 1984 and V for Vendetta explore the theme of surveillance as psychological domination rather than mere physical monitoring, yet they differ fundamentally in how completely each regime has mastered the art of making citizens police themselves. In Orwell's 1984, the telescreen — an unblinking screen in every home that cannot be switched off — is the Party's central instrument of domination. Crucially, Orwell reveals that total surveillance need not be total in practice: citizens "had to live — did live, from habit that became instinct — in the assumption that every sound was overheard." The panopticon internalises itself; citizens become their own jailers. This is reinforced through the concept of "thoughtcrime," which does not merely punish dissent but makes the act of thinking differently feel physically dangerous, collapsing the boundary between private consciousness and public crime. Winston's terrified micro-resistances — angling his body away from the screen, writing his diary in a shadowed corner — are poignant precisely because they are already futile; they reveal a man who understands he is watched even as he pretends he is not. While Orwell presents a surveillance apparatus that has all but perfected itself, McTeigue's V for Vendetta contrasts this by depicting the Norsefire regime's surveillance network — "The Eye" — as a system with exploitable structural weaknesses. V operates freely within its blindspots: his mask renders him visually illegible to identifying cameras, and his early destruction of the data archives materially dismantles the regime's ability to know its subjects. McTeigue reinforces this through chiaroscuro lighting — V is consistently filmed in deep shadow against the cold fluorescent glare of regime spaces — visually encoding the argument that control depends on visibility, and that shadow is where freedom lives. Where Orwell's Party has eliminated the possibility of an unwatched space, McTeigue insists such spaces will always exist. Both texts ultimately argue that surveillance's deepest weapon is psychological rather than optical, yet diverge on whether the psychological colonisation it produces can ever be made total.""",
b2_label='The Interior Consequences: What Surveillance Does to the Self',
body2="""In comparing the narratives, it becomes evident that 1984 emphasises the total annihilation of the interior self under perpetual observation, whereas V for Vendetta focuses on the possibility of preserving — and even rebuilding — selfhood within the watched society. Orwell demonstrates through Winston's experience that surveillance's most devastating effect is not punishment but anticipatory self-censorship: "Nothing was your own except the few cubic centimetres inside your skull." Even this last territory is under threat, since the Party's "final, most essential command" is to "reject the evidence of your eyes and ears" — surveillance ultimately demands not merely behavioural compliance but perceptual surrender. Winston's tragic ending confirms that this surrender is achievable: "He loved Big Brother" describes not a defeated man but a psychologically replaced one, his identity so thoroughly overwritten that no trace of the original survives. V for Vendetta contrasts this through Evey Hammond, whose journey from compliant BTN-watching citizen to conscious resistance traces exactly what Orwell forecloses. McTeigue uses extreme close-up cinematography during Evey's rain sequence to register the moment she achieves an interior freedom the regime cannot reclaim — her face filling the screen marks an interiority that has survived the state's attempts to erase it. Valerie's letter, passed secretly between prison cells, reinforces this through its declaration that "within that inch, we are free," insisting that the final space of selfhood cannot be confiscated if the individual refuses to surrender it. Together, both texts reveal that surveillance's ultimate ambition is the colonisation of consciousness itself — but they offer profoundly different verdicts on whether that ambition can fully succeed.""",
conclusion="""Both Orwell and McTeigue understand surveillance as a project that operates primarily on the mind rather than the body — and in this shared insight lies their deepest contribution to our understanding of political power. Yet their conclusions reflect the different historical anxieties that shaped them: Orwell, writing in the shadow of totalitarianism's first great wave, felt compelled to warn that perfected surveillance meant the end of the self; McTeigue, working amid post-9/11 surveillance politics, insists that systems of control remain systems — and systems have cracks. Read together, these texts form a dialogue rather than a contradiction: Orwell tells us what we must fear; McTeigue tells us what we must find."""
),

# ── 2 ─────────────────────────────────────────────────────────────────────────
dict(
n=2, theme='Thematic', color=BLUE,
title='Identity and the Destruction of Self',
question='(Thematic — suitable for prompts asking about how individuals are represented, or about power and the self)',
intro="""The self — the irreducible interior life of an individual — is both the primary target of authoritarian power and the last site of resistance against it. George Orwell's 1949 dystopian novel Nineteen Eighty-Four presents identity as something fragile and ultimately destroyable: under the Party's regime of surveillance and torture, Winston Smith's selfhood is methodically dismantled until nothing remains. James McTeigue's 2005 film V for Vendetta challenges this conclusion by tracing Evey Hammond's journey from fearful compliance to authentic selfhood, arguing that identity can be rebuilt even after the regime has attempted to erase it. While both texts identify the self as the true battlefield of totalitarian power, their resolutions reflect their distinct historical contexts — Orwell's post-war pessimism against McTeigue's belief in the possibility of individual and collective renewal.""",
b1_label='The Systematic Attack on Identity: Language, Memory, and Thought',
body1="""Both 1984 and V for Vendetta similarly highlight the manipulation of identity as the totalitarian regime's deepest ambition, but the impact differs: Orwell presents this assault as total and ultimately successful, while McTeigue leaves open the possibility of resistance and reconstruction. In Orwell's 1984, identity is attacked at its most fundamental level through the weaponisation of language itself. Newspeak — the Party's engineered language — is designed so that unorthodox thought becomes literally unspeakable: "every concept that can ever be needed will be expressed by exactly one word," closing down the interior vocabulary on which a distinct self depends. Orwell reinforces this through Winston's work at the Ministry of Truth, rewriting historical records so that the past perpetually conforms to the Party's present needs. Without a stable past — without memory — the self has no ground on which to stand. Winston's private assertion that "freedom is the freedom to say that two plus two make four" reveals that he understands the epistemological stakes: if the Party can make him doubt basic reality, it can unmake him entirely. V for Vendetta contrasts this through the Norsefire regime's assault on identity via cultural erasure and fear-induced conformity: banned art, state-controlled media, and the systematic suppression of minority histories collectively hollow out the population's sense of self. Yet McTeigue introduces the counter-force of recovered culture — V's collection of banned films, music, and books represents a repository of identity the regime has failed to destroy. His screening of The Count of Monte Cristo for Evey, and his cultivation of Valerie's roses, argue that suppressed selfhood can be preserved in objects and stories, kept alive to be restored. While Orwell presents language and memory as sites of total defeat, McTeigue insists they are also sites of potential reclamation.""",
b2_label='The Body as Political Site: Room 101 and the Rain',
body2="""The contrasting settings of the two texts' climactic identity transformations — Room 101 in 1984 and the rain sequence in V for Vendetta — serve to highlight fundamentally different worldviews on whether selfhood can survive totalitarian extremity. In Orwell's 1984, Room 101 represents the point at which the last reserve of interior selfhood is invaded and erased. O'Brien's declaration that "reality exists in the human mind, and nowhere else" is not merely philosophical but operational: by controlling what Winston perceives — making him accept that two plus two equals five — the Party reaches into the cubic centimetres inside his skull and rewrites what it finds. The novel's closing line, "He loved Big Brother," delivers Orwell's most devastating argument: that the self is not indestructible, that identity is not a bedrock but a structure that can be demolished and rebuilt to the oppressor's design. There is no martyrdom, no preserved resistance — only a man who is genuinely, contentedly gone. McTeigue's V for Vendetta challenges this at its most structurally intimate through Evey's transformation. V's controversial imprisonment of Evey — shaving her head, subjecting her to apparent interrogation, confronting her with manufactured fear — deliberately mirrors the regime's own techniques, and McTeigue does not flinch from this parallel. Yet the outcome is inverted: where the regime's methods produce submission, V's produce authentic liberation. When Evey steps into the rain, McTeigue's close-up cinematography and the visual metaphor of water as baptism and cleansing mark the creation of a self that has been tested and survived. Her declaration that she is "not afraid anymore" is the sentence Orwell's novel never permits Winston to speak. Together, both composers use the body's extremity as the measure of identity's resilience — and arrive at opposite verdicts.""",
conclusion="""Orwell and McTeigue both understand identity as the deepest target of authoritarian power — the final frontier beyond which resistance either persists or is extinguished entirely. Their divergence reflects not merely different political temperaments but different narrative purposes: Orwell constructs a warning, showing audiences precisely how completely the self can be unmade when the state is allowed to perfect its methods; McTeigue constructs a challenge, insisting that even in the most controlled environments a single inch of selfhood can survive if the individual chooses not to relinquish it. Together, they argue that the stories we tell about the self under pressure are among the most politically consequential stories a culture can produce."""
),

# ── 3 ─────────────────────────────────────────────────────────────────────────
dict(
n=3, theme='Thematic', color=BLUE,
title='Resistance: Individual vs Collective',
question='(Thematic — suitable for prompts about power, agency, rebellion, or the role of the protagonist)',
intro="""Authoritarian power demands conformity, yet the capacity for resistance remains a persistent human impulse — even when it is ultimately crushed. George Orwell's 1949 dystopian novel Nineteen Eighty-Four presents individual resistance as doomed: Winston Smith's solitary rebellion against the Party is anticipated, contained, and dismantled, ending in the annihilation of his will. James McTeigue's 2005 film V for Vendetta traces instead the transformation of isolated defiance into collective revolt, as V's symbolic actions progressively awaken an entire population. Both texts use their protagonists' responses to oppression to examine the limits of resistance, yet arrive at strikingly different conclusions — one a warning about the futility of rebellion against a perfected system, the other an argument that when resistance becomes a shared idea rather than an individual act, it can no longer be stopped.""",
b1_label='Individual Resistance: The Lone Rebel and the Machine',
body1="""While 1984 presents individual resistance as something the totalitarian system anticipates and consumes, V for Vendetta contrasts this by constructing a lone rebel whose individual acts are precisely calibrated to generate consequences beyond himself. In Orwell's 1984, Winston Smith's acts of resistance — his diary, his affair with Julia, his reading of Goldstein's forbidden book, his belief in objective truth — are compelling precisely because they are also comprehensively futile. The novel's most devastating structural irony is that every resource Winston uses to resist becomes, under the Party's gaze, an instrument of his destruction. The room above Charrington's shop, where Winston and Julia seek refuge, is itself a surveillance trap; the Brotherhood, which promises organised resistance, is a Party fiction designed to identify and harvest dissidents; even O'Brien, Winston's hoped-for ally, is the Party's most effective agent. When the telescreen behind the picture speaks — "You are the dead" — it confirms what the novel has been silently demonstrating: the Party doesn't merely defeat resistance, it engineers it, allowing it just enough air to identify itself before extinguishing it. In contrast, V for Vendetta constructs V as a rebel who understands that individual action is only meaningful insofar as it generates collective consequence. V's destruction of the Old Bailey is not merely symbolic demolition but a deliberate theatrical act, staged to Beethoven's Fifth Symphony and timed for maximum public impact — designed to be seen, discussed, and remembered. McTeigue's use of cross-cutting between V's methodical preparations and the Norsefire regime's increasingly frantic responses positions V as the controlling intelligence of his own narrative, always one step ahead. Unlike Winston, V does not seek solidarity in secret rooms; he broadcasts, performs, and leaves a mask for others to wear. Both texts use their rebel protagonists to ask whether the individual can meaningfully challenge the state — but only one answers yes.""",
b2_label='Collective Potential: The Proles and the Crowd',
body2="""The contrasting treatments of collective resistance in the two narratives reflect each composer's deepest belief about whether political change is achievable, revealing sharply divergent assessments of human solidarity. In Orwell's 1984, the proles — who constitute eighty-five per cent of Oceania's population — represent the theoretically decisive force that never materialises. Winston's observation that "until they become conscious they will never rebel, and until after they have rebelled they cannot become conscious" exposes a structural paradox at the heart of the novel's politics: collective resistance requires the very political consciousness that the regime exists to prevent. The proles' lives are consumed by Prolefeed — sport, lottery, and sentiment — and Orwell presents no moment of collective awakening, no network of solidarity, no inherited tradition of resistance. They are the force that could end the Party and will never do so. V for Vendetta invests entirely in the opposite argument. McTeigue's climactic sequence — in which hundreds of ordinary Londoners don Guy Fawkes masks and march on Parliament in the face of armed soldiers — enacts the thesis that an idea, once released into a population, cannot be contained. The aerial shot of the masked crowd is the film's most politically potent image: from above, the masks are identical and innumerable, rendering the movement impossible for the state to identify, individualise, or suppress. The regime's soldier, ordered to fire on the crowd, lowers his gun — registering the moment the state's capacity for violence fails against the collective withdrawal of consent. Together, both composers argue that collective resistance is the only form capable of challenging totalitarian power; they differ only on whether it is ever achievable. Orwell says no; McTeigue says it requires a single person willing to be the first domino.""",
conclusion="""Orwell and McTeigue offer their audiences two different but complementary truths about resistance. 1984 is the anatomy of failure — a precise account of how perfectly calibrated totalitarian power renders every individual act of rebellion not merely futile but actively useful to the system it opposes. V for Vendetta is the anatomy of possibility — an argument that resistance becomes unstoppable when it transcends the individual who initiates it and becomes a symbol that anyone can carry. Read together, the texts suggest that understanding why resistance fails is a prerequisite for understanding how it might succeed — and that both forms of knowledge are essential."""
),

# ── 4 ─────────────────────────────────────────────────────────────────────────
dict(
n=4, theme='Thematic', color=BLUE,
title='Language, Truth, and Propaganda',
question='(Thematic — suitable for prompts about representation, narrative, or the power of storytelling)',
intro="""Language is not merely a tool of communication — in the hands of a totalitarian state, it becomes the primary instrument of control. George Orwell's 1949 dystopian novel Nineteen Eighty-Four depicts a regime that has weaponised language through Newspeak, deliberately narrowing vocabulary to make unorthodox thought literally unspeakable, while rewriting history to ensure the past conforms to the Party's needs. James McTeigue's 2005 film V for Vendetta similarly presents a regime dependent on propaganda and suppressed truth, but allows for a counter-narrative: V's pirate broadcast reclaims language as a site of resistance. Both texts argue that the battle for political freedom begins with the battle for truth — yet Orwell's regime succeeds in conquering it entirely, while McTeigue leaves open the possibility that truth, once spoken, cannot be permanently silenced.""",
b1_label='The Weaponisation of Language: Narrowing the Possible',
body1="""Both 1984 and V for Vendetta explore the manipulation of truth through propaganda, but the impact differs: in 1984 truth is controlled so thoroughly that it ceases to exist as a concept, while in V for Vendetta the exposure of suppressed truth becomes the catalyst for revolutionary change. In Orwell's 1984, the Party's most profound achievement is not military or economic but linguistic: Newspeak is designed so that "thoughtcrime" is literally impossible because there will be no words in which to express it. Syme, Winston's colleague, explains the ambition with chilling enthusiasm — "every concept that can ever be needed will be expressed by exactly one word, with its meaning rigidly defined" — making Newspeak not merely a language but the destruction of language, a systematic narrowing of the possible. Orwell reinforces this through Winston's work at the Ministry of Truth, where he rewrites newspaper articles, alters statistical records, and disappears inconvenient historical figures into the memory hole. The Party slogan "Who controls the past controls the future: who controls the present controls the past" reveals through chiasmus that the regime understands history not as a record but as a weapon — and has seized it completely. V for Vendetta similarly presents a regime that controls its population through the monopolisation of public narrative: the British Television Network (BTN) broadcasts government-approved reality into every home, and the Chancellor's speeches manufacture consent through fear. Yet McTeigue introduces a critical structural difference: the regime's control of language is not total. V hacks the BTN to broadcast his own pirate address to the nation — an act that is simultaneously technological, political, and rhetorical, demonstrating that the state's narrative can be interrupted, its frequency seized, its audience redirected. Artists use lies to tell the truth, V declares — positioning counter-narrative not as a luxury but as the foundational act of political resistance.""",
b2_label='The Counter-Narrative: Writing Back Against Power',
body2="""In comparing the two narratives, it becomes evident that 1984 emphasises the impossibility of a sustainable counter-narrative under total linguistic control, whereas V for Vendetta focuses on the transformative power of a single act of truth-telling to catalyse irreversible change. In Orwell's 1984, Winston's diary represents his most private and consequential act of counter-narrative — a deliberate attempt to speak truth to himself in a world that has made truth illegal. His entry that "freedom is the freedom to say that two plus two make four" is not a political manifesto but an epistemological lifeline, the smallest possible assertion of reality against the Party's reconstruction of it. Yet the diary fails as resistance precisely because it remains private: language that cannot be shared cannot build solidarity, and Winston's counter-narrative, however authentic, reaches no one and changes nothing. The novel's closing lines — "He loved Big Brother" — represent the ultimate defeat of counter-narrative: Winston no longer possesses the language with which to tell himself the truth. V for Vendetta presents the opposite trajectory, in which a single act of unauthorised truth-telling sets in motion consequences that cannot be recalled. V's pirate broadcast reaches the entire population simultaneously, shattering the regime's information monopoly in a single transmission. McTeigue reinforces the power of this with the film's recurring use of Guy Fawkes imagery and the incantation "Remember, remember the fifth of November" — positioning V's narrative as one that connects to a centuries-old tradition of resistance, giving it historical depth and cultural resonance that the regime cannot simply erase. Whereas Orwell shows us how truth is murdered by a state that controls all language, McTeigue shows that truth, once released into the public sphere, can survive even the death of the individual who released it.""",
conclusion="""Both Orwell and McTeigue understand that language is the terrain on which all other political battles are ultimately decided — that control of words is control of thought, and control of thought is control of everything. Orwell warns that this battle can be lost: that a regime sophisticated enough to engineer language itself can construct a world in which truth has no purchase. McTeigue offers a counterargument: that narrative, once cracked open, floods back. Together, the texts argue that the most politically consequential act available to any individual is not violence or protest but the insistence on speaking truthfully — and that this act, despite everything, retains the power to change the world."""
),

# ── 5 ─────────────────────────────────────────────────────────────────────────
dict(
n=5, theme='Thematic', color=BLUE,
title='Fear as a Mechanism of Power',
question='(Thematic — suitable for prompts about power, control, propaganda, or the representation of government)',
intro="""Fear is the most efficient instrument of authoritarian power — it requires no army in the street if the army lives inside the citizen's mind. George Orwell's 1949 dystopian novel Nineteen Eighty-Four constructs a regime whose dominance rests on manufactured terror: the telescreen's surveillance, the threat of Room 101, and the concept of thoughtcrime ensure citizens police themselves through internalised dread. James McTeigue's 2005 film V for Vendetta presents the same mechanism, but argues — through V's declaration that governments should be afraid of their people — that the relationship of terror can be reversed. Both texts examine how fear shapes human behaviour under oppression, yet offer contrasting visions: one in which fear is total and inescapable, the other in which it can be directly confronted and dismantled through collective courage.""",
b1_label='Manufacturing Fear: The Architecture of Dread',
body1="""Both 1984 and V for Vendetta explore the theme of state-manufactured fear as the foundation of authoritarian control, yet they differ in how sustainably each regime can maintain it. In Orwell's 1984, fear is not incidental to the Party's rule but its primary product and mechanism. The telescreen ensures that citizens cannot know when they are being observed — meaning they must always assume they are, generating a constant low-level terror that requires no active effort from the state to maintain. The concept of thoughtcrime extends this fear into the last private space: even thoughts are criminal, making the mind itself a site of danger. Orwell renders the physical architecture of fear through the Ministry of Love — a windowless building without darkness, where the lights never turn off, where sleep deprivation and physical pain are the instruments of psychological remoulding. Room 101, which contains "the worst thing in the world" uniquely calibrated to each individual, represents the final, inescapable form of the regime's power: a terror so personalised that no one can prepare for or resist it. The Party does not need to use Room 101 on everyone; the knowledge of its existence is sufficient. V for Vendetta similarly establishes a regime whose power rests on manufactured fear: the Norsefire government maintains control through state-broadcast messages from Chancellor Sutler, whose screaming face fills enormous screens in a deliberate echo of the Nuremberg rallies, and through the knowledge that the secret police — "the Finger" — can make dissenters disappear without trial. McTeigue reveals, however, that this fear was itself constructed from a lie: the St Mary's virus, used to justify Norsefire's seizure of emergency power, was engineered by the regime itself — fear as a political product, manufactured and released for electoral purposes. This revelation is crucial: it positions the regime's fear not as a natural or inevitable force but as a human construction, and therefore something that can be exposed, dismantled, and replaced.""",
b2_label='Fear Reversed: From Paralysis to Courage',
body2="""The contrasting treatments of fear's effects on individual characters in the two texts serve to highlight each composer's fundamental position on whether the human capacity for courage can overcome state-engineered terror. In Orwell's 1984, fear produces total paralysis of the will. Winston understands, intellectually, that the Party's power rests on the consent of its subjects — yet this understanding changes nothing, because understanding and acting are no longer connected. The telescreen and the threat of Room 101 have produced a citizenry for whom resistance is not merely dangerous but psychologically inconceivable. Even Winston's rebellion, such as it is, is contaminated by fear from the outset: he begins his diary with the knowledge that writing it is a death sentence, and his relationship with Julia is shadowed throughout by the certainty of eventual discovery. When O'Brien forces Winston to confront his deepest terror — rats — the last resistance of the self collapses not through argument or force but through the overwhelming, primal reality of fear itself. V for Vendetta traces the opposite trajectory through Evey Hammond, whose arc moves from fear to its deliberate and achieved absence. V's controversial imprisonment and apparent torture of Evey is designed not to break her but to bring her to the point of genuine fearlessness — the moment she accepts that she would rather die than betray herself. McTeigue frames this through close-up cinematography and the visual symbolism of Evey stepping into rain: the camera's shift from tight confinement to open sky mirrors the psychological expansion of someone who has passed through fear and emerged on the other side. "I'm not afraid anymore," she declares — a sentence Orwell's novel never permits Winston to speak. Together, both texts reveal that fear's power over the individual self is the authoritarian regime's ultimate weapon; they diverge only on whether it can ever be overcome.""",
conclusion="""Orwell and McTeigue construct fear as the invisible architecture of authoritarian control — the force that makes walls unnecessary because the prisoners have internalised them. Orwell's regime has perfected fear to the point where it is self-sustaining, requiring no ongoing investment from the state to maintain its grip on the individual mind. McTeigue's Norsefire, by contrast, has constructed its fear on a lie that can be exposed — and once exposed, the fear it generated begins to dissolve. Together, the texts argue that understanding the manufactured nature of political fear is the first condition of freedom, and that the moment a population chooses not to be afraid — as Evey does, as the masked crowd does — is the moment the regime's power begins to fail."""
),

# ── 6 ─────────────────────────────────────────────────────────────────────────
dict(
n=6, theme='Thematic', color=BLUE,
title='Memory and History as Sites of Resistance',
question='(Thematic — suitable for prompts about truth, storytelling, or the role of the past in shaping the present)',
intro="""To control the past is to control the future — and in this lies the most powerful weapon available to any authoritarian regime. George Orwell's 1949 dystopian novel Nineteen Eighty-Four presents a society where memory has been weaponised: the Ministry of Truth rewrites historical records, ensuring the past conforms to the Party's needs and leaving citizens no foundation from which to imagine change. James McTeigue's 2005 film V for Vendetta counters this by positioning memory as an instrument of resistance: V's invocation of the Guy Fawkes tradition and Valerie's letter passed between prison cells demonstrate that suppressed histories can survive and fuel revolution. Together, both texts reveal that the struggle between oppression and freedom is ultimately a struggle over who controls the stories a society tells about itself — and what those stories make possible.""",
b1_label='The Erasure of Memory: How Regimes Destroy the Past',
body1="""Both 1984 and V for Vendetta explore how authoritarian regimes use the control of history and memory as instruments of domination, yet they differ in whether the erasure of the past is depicted as total or as ultimately incomplete. In Orwell's 1984, the Ministry of Truth — whose purpose is the continuous rewriting of historical records — represents the Party's most sophisticated mechanism of control. Winston's job is to alter newspaper archives so that past predictions, promises, and statistics always conform to the Party's current position; when a person is "unpersoned," every trace of their existence is removed from the record as thoroughly as if they had never been born. The Party slogan "who controls the past controls the future: who controls the present controls the past" reveals the circularity of this strategy: the past is not a fixed reality but a resource that power rewrites continuously. Orwell demonstrates the personal cost of this through Winston's fragmented, unreliable memories — he cannot recall with certainty what life was like before Big Brother, cannot verify whether his childhood impressions of a freer world are accurate or confabulated. Without a verifiable past, he has no foundation for imagining an alternative future; without an alternative future, resistance is directionless and ultimately hollow. V for Vendetta similarly presents a regime that suppresses historical truth — the origin of the St Mary's virus, the existence of the Larkhill detention facility, the persecution of ethnic and sexual minorities — yet McTeigue introduces a critical difference: suppression is not the same as erasure. The destroyed histories have survived in fragments: in V's underground gallery of banned art, in Valerie's letter written on toilet paper and preserved through the most extreme circumstances, in the street tradition of Guy Fawkes night that the regime has been unable to fully extinguish. Where Orwell presents a regime that has successfully closed the past, McTeigue argues that memory is more durable than any regime's capacity to erase it.""",
b2_label='Memory as Weapon: The Act of Remembering as Resistance',
body2="""The contrasting uses of memory by each text's central resistant figures — Winston Smith's desperate attempts to recall and Valerie's deliberate act of recording — reveal the different political functions each composer assigns to the act of remembering. In Orwell's 1984, Winston's private memories are among his most precious and most fragile forms of resistance. He treasures the paperweight — "a chunk of history that they had forgotten to alter" — as a physical object that connects him to a past that predates the Party's control. His diary is an act of bearing witness: "To the future or to the past, to a time when thought is free" — he writes for a reader who may never exist, preserving a record of his consciousness against the regime's efforts to remake it. Yet Orwell gives this act of memory no political consequence: Winston's record will be destroyed along with him, his memories are too fragmented to constitute genuine historical knowledge, and the glass paperweight — symbol of the past's fragile persistence — is shattered when the Thought Police arrive. Memory as individual act is heroic but ineffectual. McTeigue's treatment of memory through Valerie's letter inverts this. Written in a prison cell and passed between prisoners — its physical survival an act of extraordinary will and solidarity — Valerie's letter is a piece of testimony that does not merely record but transforms. When Evey reads it, she is changed: the letter's account of what Valerie chose to preserve of herself even in extremity — "my integrity," "my love of a woman" — gives Evey the framework to understand her own resistance. McTeigue reinforces the political power of shared memory through V's invocation of the Guy Fawkes rhyme at the film's opening: "Remember, remember the fifth of November" positions the act of cultural remembrance as itself a revolutionary practice, connecting V's present rebellion to a centuries-old tradition of principled resistance. Together, both texts argue that memory is a political battleground — and that the side which controls it controls the future.""",
conclusion="""Orwell and McTeigue both understand that the past is not merely history but a resource — the raw material from which present identity and future possibility are constructed. Orwell's deepest warning is that a sufficiently powerful state can destroy this resource, leaving citizens with no historical ground from which to imagine alternatives to the present arrangement. McTeigue's counterargument is that memory is more resilient than any regime's efforts at erasure — that it survives in objects, letters, songs, and traditions precisely because it matters too much to the human spirit to be entirely destroyed. Read together, the texts insist that the act of remembering — and of telling stories that preserve what power wants forgotten — is among the most consequential political acts available to any individual."""
),

# ── 7 ─────────────────────────────────────────────────────────────────────────
dict(
n=7, theme='To What Extent', color=RED,
title='Inescapability of Totalitarian Power',
question='To what extent do both texts suggest that totalitarian power is ultimately inescapable?',
intro="""The architecture of authoritarian control is designed to feel inevitable — yet the degree to which it actually is reveals the deepest philosophical difference between these two landmark dystopian narratives. George Orwell's 1949 novel Nineteen Eighty-Four presents totalitarian power as effectively absolute: Winston Smith's every attempt to find a crack in the system is revealed to be a trap, and the novel's devastating conclusion — "He loved Big Brother" — forecloses any possibility of escape. James McTeigue's 2005 film V for Vendetta significantly challenges this, depicting a regime whose surveillance and propaganda contain fatal flaws that one individual can exploit. While both composers present authoritarian power as devastatingly effective, McTeigue ultimately argues that no system of control is fully inescapable — provided there remain those willing to test its limits.""",
b1_label='The Case for Inescapability: When the System Has No Outside',
body1="""Both 1984 and V for Vendetta present totalitarian regimes of immense reach and sophistication, yet to a significant extent 1984 constructs a system of control so complete that it leaves no genuine outside — no space in which resistance can take root and survive. Orwell's most chilling structural argument is that the Party has penetrated even the spaces that appear to lie beyond its reach. Winston believes the room above Charrington's junk shop is a sanctuary — its absence of telescreens, its view of an ordinary street, its space for genuine intimacy — yet it is a Party trap, the picture concealing a hidden screen. He believes O'Brien is a fellow dissident, a member of the Brotherhood, an ally in a genuine underground — yet O'Brien is the Party's most effective agent, who has been watching Winston "for seven years." Even the Brotherhood itself is a fiction, designed not to enable resistance but to identify and harvest it. Orwell reinforces the totality of the Party's reach through O'Brien's philosophical declaration: "Reality exists in the human mind, and nowhere else" — meaning that the Party, by controlling minds, controls reality itself. There is no appeal to objective truth, no external standard against which the Party's version can be measured, because the Party has defined what measurement means. Winston's final psychological surrender — "He loved Big Brother" — is therefore not a defeat but a completion: the system has done exactly what it was designed to do. V for Vendetta presents a regime of comparable ambition, yet to a lesser extent — and this lesser extent is decisive. The Norsefire regime relies on surveillance networks, state media, and secret police, but McTeigue reveals structural vulnerabilities that Orwell never permits in Oceania: V is able to move freely, to access and destroy government archives, to hack national broadcasts, and to survive for years under the Eye's gaze. The regime's foundational lie — the engineered St Mary's virus — is ultimately exposed, demonstrating that a system built on fabrication can be undone by the revelation of truth. The extent to which totalitarian power is inescapable, McTeigue suggests, depends entirely on whether the system has successfully closed all its exits.""",
b2_label='Points of Fracture: Where the Armour Fails',
body2="""The contrasting fates of the rebel figures in each text illuminate the degree to which each totalitarian system retains vulnerabilities, revealing that power's inescapability is a question of design rather than an inevitability. In Orwell's 1984, every apparent fracture in the Party's power proves to be a controlled opening — a door that leads deeper into the machine rather than out of it. Winston's hope in the proles, the one class large enough to overthrow the Party, is shown to be unfounded: "Until they become conscious they will never rebel, and until after they have rebelled they cannot become conscious" — a circular paradox from which the novel offers no exit. Even his private internal resistance — his diary, his love for Julia, his belief that 2+2=4 — is systematically dismantled, not because the Party discovers it, but because the Party allowed it, knowing that private resistance eventually presents itself for destruction. The inescapability of Oceania's power is not contingent but structural: it has been designed to have no outside. V for Vendetta, by contrast, depicts a totalitarian system that has not achieved this closure. Inspector Finch's investigation leads him to the truth about Larkhill and St Mary's — the regime's own agent uncovers the lie at the regime's heart, demonstrating that the system cannot fully control the consequences of its own actions. McTeigue uses cross-cutting to show V always ahead of the state's response, always exploiting the gap between what the regime knows and what it does not — and these gaps, the film argues, are inherent to any human-made system of control. The degree to which power is inescapable, both texts ultimately suggest, is the degree to which it has succeeded in eliminating all gaps. Orwell's Party has; McTeigue's Norsefire has not — and this single difference determines everything.""",
conclusion="""To the extent that totalitarian power is depicted as inescapable, both texts agree that this quality depends not on force but on the total colonisation of thought, language, and reality itself. Orwell's Party has achieved this colonisation; McTeigue's Norsefire has attempted it but retained the cracks that make systems vulnerable. Taken together, the two texts offer a sobering but not entirely hopeless account of authoritarian power: it is most inescapable when it is most complete — and most vulnerable at precisely the points where it is not. The question each text poses to its audience is whether they can find, and widen, those points before the system achieves completion."""
),

# ── 8 ─────────────────────────────────────────────────────────────────────────
dict(
n=8, theme='To What Extent', color=RED,
title='Resistance as a Meaningful Act',
question='To what extent do Orwell and McTeigue present resistance as a meaningful act?',
intro="""The act of resistance against authoritarian power carries radically different weight depending on the world in which it occurs, and the question of whether defiance can ever be meaningful is one that fundamentally divides these two dystopian narratives. George Orwell's 1949 novel Nineteen Eighty-Four presents resistance as ultimately futile: Winston Smith's private acts of defiance — his diary, his relationship with Julia, his belief in objective truth — are each anticipated and contained by the Party. James McTeigue's 2005 film V for Vendetta argues to a significant extent that resistance is not only meaningful but transformative, as V's symbolic acts catalyse a collective awakening that dismantles the Norsefire regime. Together, the texts suggest that resistance's meaningfulness depends less on its form than on whether it can transcend the individual who initiates it.""",
b1_label='The Limits of Meaningful Resistance: Orwell\'s Closed World',
body1="""To a significant extent, Orwell's 1984 argues that resistance is not merely meaningless but that the very desire to resist is the mechanism through which the totalitarian state identifies and destroys its opponents — making the act of defiance, paradoxically, a form of self-destruction. Winston's resistance takes multiple forms — his diary, his relationship with Julia, his engagement with the Brotherhood — and each is, in retrospect, a step deeper into the trap the Party has set. The diary, which Winston begins with the romantic notion that "to the future or to the past, to a time when thought is free," is his most private act of resistance and the one the Party has already anticipated; when the telescreen speaks in the room above the junk shop, his words are the evidence of his crime. His relationship with Julia, which he understands as resistance "from the waist downwards," is similarly contained: Julia's pragmatic individualism ("I only rebel from the waist downwards") offers no political horizon and is dismantled the moment Room 101 removes each from the other's loyalty. Most devastatingly, Winston's intellectual resistance — his insistence that "freedom is the freedom to say that two plus two make four" — is neutralised by O'Brien's demonstration that the mind can be remade to accept any equation the Party decrees. In this sense, Winston's resistance is not meaningless in the moral sense — his struggle is genuine and his comprehension of what is at stake is clear — but it is meaningless in the political sense: it produces no consequence, changes nothing, and ends with his own transformation into a man who loves what he fought. To this extent, Orwell's text delivers a deeply uncomfortable argument: resistance, without the conditions that make it effective, is not meaningful action but tragic gesture.""",
b2_label='The Transformative Power of Symbolic Resistance: McTeigue\'s Answer',
body2="""V for Vendetta significantly challenges Orwell's pessimistic conclusion by constructing resistance as meaningful to the degree that it is symbolic, transmissible, and designed to outlast the individual who initiates it. V's acts of resistance are distinguished from Winston's in one crucial dimension: they are not private but spectacular. The destruction of the Old Bailey, staged to Beethoven's Fifth and timed for maximum public visibility, is not an act of sabotage but an act of theatre — designed to be seen, discussed, and remembered. McTeigue's use of the Beethoven leitmotif reinforces this: the Fifth Symphony's opening notes encode the letter V in Morse code, connecting V's individual act to an existing cultural vocabulary of resistance that the population already shares. This theatricality is V's response to Orwell's dilemma: if private resistance is easily contained, then public, symbolic resistance — resistance designed to circulate rather than hide — may be harder to suppress. The film's climax enacts this argument: V's death does not end the resistance because V was never the resistance — the mask is. When the crowd dons Guy Fawkes masks and advances on Parliament, they demonstrate that V's greatest act of resistance was not the destruction of any building but the creation of a symbol that anyone could wear. McTeigue uses the aerial shot of the masked crowd to make this visible: from above, the individuals are indistinguishable — the idea has become the actor, and the idea cannot be shot. To the extent that resistance is meaningful, both texts suggest, it depends on whether the rebel understands this distinction: Winston fights as a person and is destroyed as a person; V fights as an idea and survives as one.""",
conclusion="""To the extent that resistance is meaningful, both texts agree that this depends on whether it can generate consequences beyond the individual who performs it. Orwell argues that in a sufficiently closed system, it cannot — that the Party's penetration of every apparent refuge means that all resistance, however sincere, eventually serves the system's ends. McTeigue argues that resistance becomes meaningful precisely when it transcends personal survival and invests itself in something transmissible: a symbol, an idea, a story. Together, the texts suggest that resistance is most meaningful not when it is most heroic but when it is most designed — when the rebel understands that the goal is not to survive the state, but to create the conditions under which others can."""
),

# ── 9 ─────────────────────────────────────────────────────────────────────────
dict(
n=9, theme='To What Extent', color=RED,
title='The Individual as Powerless Against Authoritarian Control',
question='To what extent do both texts present the individual as powerless against the forces of authoritarian control?',
intro="""The individual standing alone against the machinery of the state is one of the defining images of political literature — yet how powerless that individual truly is depends entirely on which of these two dystopian worlds they inhabit. George Orwell's 1949 novel Nineteen Eighty-Four presents the individual as almost entirely powerless: Winston Smith possesses intelligence, desire, and the will to resist, yet every resource he deploys is anticipated and turned against him by the Party. James McTeigue's 2005 film V for Vendetta substantially complicates this, depicting a single individual who is extraordinarily effective against a comparable regime. Both composers acknowledge the immense reach of authoritarian systems, yet diverge on whether the individual, equipped with symbolic purpose and the willingness to sacrifice, can ever genuinely challenge the state.""",
b1_label='The Weight of the System: How Power Overwhelms the Individual',
body1="""To a considerable extent, both texts present the individual as profoundly and structurally disadvantaged against totalitarian authority — yet they differ in whether this disadvantage is presented as absolute or merely severe. In Orwell's 1984, the individual is rendered powerless through the systematic elimination of every resource that might otherwise sustain resistance: community, history, language, and the certainty of one's own perceptions. Winston's powerlessness is not physical — the Party does not crush him with superior numbers — but epistemological and psychological. When O'Brien holds up four fingers and asks how many Winston sees, and Winston is unable to insist on the answer he knows to be correct, Orwell demonstrates that the Party has achieved something more devastating than physical domination: it has dismantled the individual's capacity for self-authorising perception. "Nothing was your own except the few cubic centimetres inside your skull," Winston observes — and even this is taken. The concept of doublethink ensures that the individual cannot use rationality as a basis for resistance, since the mind has been trained to accept contradictions; the concept of thoughtcrime ensures that the mere desire to resist makes one criminal before any act occurs. To a significant extent, the individual in Orwell's world is not merely powerless but structurally prevented from recognising the full extent of their powerlessness. V for Vendetta acknowledges the same asymmetry — the Norsefire regime commands surveillance networks, secret police, state media, and the legal authority to "disappear" dissidents — yet presents the individual as substantially less powerless when equipped with the right combination of resources: knowledge of the regime's crimes, strategic intelligence, and, crucially, the willingness to operate as symbol rather than as person. V's power is not individual in the conventional sense; it is the power of someone who has already accepted that they are dead and therefore acts with a freedom unavailable to those who still have survival to lose.""",
b2_label='Individual Acts and Their Consequences: Power Where Least Expected',
body2="""The individual acts of resistance in each text — and their respective consequences — illuminate the degree to which personal agency can ever meaningfully challenge authoritarian power, revealing a fundamental disagreement between the two composers about the conditions under which individuals retain genuine capacity for change. In Orwell's 1984, Winston's moments of apparent individual agency are systematically revealed to be illusory. He chooses O'Brien as an ally — O'Brien has selected himself. He chooses the room above the junk shop as a refuge — it is already equipped with a hidden telescreen. He chooses to read Goldstein's book — the Brotherhood is a Party construction, the book written by O'Brien himself. Each apparent exercise of Winston's individual will turns out to be the Party's will operating through him, leading him exactly where the regime wants him to go. The deepest expression of his powerlessness is that he cannot even choose how to resist — every available option has been pre-approved by those who intend to destroy him. V for Vendetta substantially challenges this reading of individual power by constructing V as an individual whose acts have measurable, cumulative, and ultimately decisive consequences. Each of V's actions — the destruction of the Old Bailey, the pirate broadcast, the delivery of masks to the population, the execution of those who operated Larkhill — is chosen and executed freely, and each shifts the political landscape in ways the regime cannot fully counteract. McTeigue uses the domino sequence to visualise this causality: V's plan, once set in motion, produces cascading consequences that cannot be reversed. Most significantly, V's death — the ultimate expression of individual powerlessness against the state — is also the trigger for the regime's final collapse, demonstrating that the individual can be simultaneously destroyed and victorious. To the extent that the individual is powerless, both texts suggest, this power depends on whether they have found a way to make their acts transmissible beyond their own survival.""",
conclusion="""To the extent that both texts present individuals as powerless, this powerlessness is shown to be situational rather than absolute — contingent on the design of the system they oppose and the degree to which they have found a way to act that exceeds their individual capacity. Orwell presents a system so perfectly designed that individual power has been entirely foreclosed; McTeigue presents one imperfect enough that an individual with the right tools and the right mindset can crack it. Together, the texts argue that the question of individual power under authoritarian rule is not merely political but philosophical: it depends on what kind of power is being exercised. Physical, personal, survival-oriented power is easily crushed. Symbolic, transmissible, idea-driven power is considerably harder to destroy."""
),

# ── 10 ────────────────────────────────────────────────────────────────────────
dict(
n=10, theme='To What Extent', color=RED,
title='Societies Surrendering Freedom for Safety',
question='To what extent do both texts suggest that societies willingly surrender their freedoms in exchange for safety and order?',
intro="""Authoritarian regimes rarely seize power by force alone — they are frequently invited in by populations who trade freedom for the promise of safety, and both texts examine this troubling exchange with urgent relevance. George Orwell's 1949 novel Nineteen Eighty-Four presents a society so thoroughly conditioned that citizens have ceased to remember freedom, actively participating in their own surveillance without coercion. James McTeigue's 2005 film V for Vendetta engages with this exchange directly: the Norsefire regime rose to power through a manufactured bioterror crisis, exploiting a population desperate for order and security. While both texts explore how fear enables the surrender of freedom, McTeigue extends the argument by suggesting that populations can reclaim what they have voluntarily surrendered — if they are willing to accept the cost of doing so.""",
b1_label='The Mechanics of Voluntary Surrender: How Freedom Is Given Away',
body1="""To a significant extent, both 1984 and V for Vendetta suggest that societies do not lose their freedoms — they surrender them, and that this voluntary dimension of authoritarian consolidation is what makes it most difficult to resist. In Orwell's 1984, Oceania's citizens do not appear to have actively chosen surveillance, doublethink, or thought control — yet Orwell reveals, through characters such as Parsons and the women of the Anti-Sex League, that many citizens are genuinely enthusiastic participants in their own surveillance. Parsons, Winston's neighbour, is eventually denounced to the Thought Police by his own daughter — and his response is not anger but pride: "I'm glad they got me before it went any further." This moment is among the novel's most disturbing, revealing a population that has so thoroughly internalised the regime's values that it polices itself not under duress but out of genuine belief. The historical processes by which this situation arose are deliberately obscured — the Party has rewritten the past — but Goldstein's book suggests that the regime consolidated power during a period of social crisis, when populations accepted extraordinary measures as temporary necessities. The temporary became permanent; the necessity became nature. V for Vendetta is more explicit about this process. In V's pirate broadcast, he tells the people of Britain directly: "I know why you did it... you were afraid." The Norsefire regime came to power after engineering the St Mary's virus outbreak — deliberately manufacturing a crisis severe enough to make the population beg for the strong leadership that Chancellor Sutler offered. McTeigue presents this as a mirror held up to contemporary audiences: the film's post-9/11 context makes explicit the argument that democracies under sufficient fear can vote away their own civil liberties. The surrender of freedom for safety is shown to be not a weakness unique to fictional dystopias but a recurring historical pattern with real-world precedents.""",
b2_label='The Cost of Compliance and the Possibility of Reclamation',
body2="""The contrasting conclusions of the two texts on whether populations can reclaim surrendered freedoms reveal each composer's deepest conviction about human agency and the reversibility of political choices. In Orwell's 1984, the population's surrender of freedom has been so complete and has operated for so long that reclamation appears structurally impossible. The proles, who constitute the majority of Oceania's population and whose size alone would make them capable of revolution, cannot reclaim their freedoms because the conditions for political consciousness have been systematically eliminated: they lack the education, the communication networks, the historical memory, and the political vocabulary to organise. Winston's observation that "until they become conscious they will never rebel, and until after they have rebelled they cannot become conscious" identifies a closed loop from which the novel offers no exit. More troublingly, Orwell suggests that the desire to reclaim freedom itself diminishes over time: citizens like Parsons do not experience their condition as loss because they have lost the vocabulary — and eventually the memory — of what was surrendered. The paperweight that Winston treasures as a remnant of the pre-Party past is shattered on the floor when the Thought Police arrive, and with it the last physical trace of an alternative world. V for Vendetta substantially complicates this by insisting that reclamation is possible but requires the population to first acknowledge its own complicity. V's broadcast does not merely expose the government's crimes; it indicts the population: "If you're looking for the guilty, you need only look into a mirror." McTeigue frames this as a precondition for genuine political renewal — the population cannot reclaim its freedom without first accepting that it surrendered it. The film's climax demonstrates that once this acceptance occurs, the energy it releases is decisive: the crowd's advance on Parliament represents a collective reclamation of sovereignty, the voluntary reassertion of the freedom that was voluntarily given away.""",
conclusion="""To the extent that both texts suggest societies willingly surrender their freedoms, this suggestion carries a warning that resonates beyond fiction: that the conditions for authoritarian power are not manufactured by tyrants alone but created by populations choosing safety over freedom in moments of crisis. Orwell insists that once this surrender is complete and time has erased the memory of what was given up, reclamation becomes impossible. McTeigue insists it is never too late — but requires honesty about complicity. Together, the texts issue a shared challenge to their audiences: to recognise the exchange before it is complete, and to understand that the most dangerous moment is not when the regime demands your freedom, but when you offer it."""
),

# ── 11 ────────────────────────────────────────────────────────────────────────
dict(
n=11, theme='To What Extent', color=RED,
title='Individual Sacrifice and Collective Change',
question='To what extent do both texts use the figure of the rebel to explore the relationship between individual sacrifice and collective change?',
intro="""The rebel — isolated, idealistic, and willing to risk everything — is the primary lens through which both texts examine the possibility of political change, yet the degree to which individual sacrifice can translate into collective transformation reveals the most significant divergence between these two dystopian visions. George Orwell's 1949 novel Nineteen Eighty-Four presents Winston Smith as a rebel whose sacrifice yields nothing: his resistance is contained, his body broken, and his mind remade, with no visible ripple of change left behind. James McTeigue's 2005 film V for Vendetta takes a profoundly different position: V's willingness to die for an idea directly enables the collective awakening of an entire population. Both texts use the rebel not to celebrate heroism but to test whether individual sacrifice can ever be sufficient — and they arrive at very different, deeply instructive answers.""",
b1_label='The Rebel Who Changes Nothing: Winston and the Limits of Individual Sacrifice',
body1="""To a significant extent, Orwell's construction of Winston Smith as a rebel is designed to demonstrate the conditions under which individual sacrifice produces no collective consequence — and to insist that these conditions are the normal state of affairs under totalitarianism. Winston's sacrifice is genuine: he takes genuine risks, suffers genuinely, and maintains for as long as he is able a genuine commitment to truth. His insistence that "two plus two make four" in the face of a regime that asserts five is a form of moral courage, and his willingness to accept pain rather than immediately surrender is admirable in human terms. Yet Orwell gives this sacrifice no political product. There is no ripple from Winston's resistance: no one else is inspired, no information is transmitted, no network is strengthened, no consciousness raised. This is partly because Winston's resistance is structurally private — his diary reaches no one, his alliance with Julia is bilateral and self-contained, his contact with O'Brien is a trap rather than a genuine solidarity. But it is also because the Party has engineered a world in which private sacrifice cannot scale into collective action: the proles remain inert, the Brotherhood does not exist, and the population's consciousness is too thoroughly managed for any single act of defiance to introduce a new possibility. When Winston is finally broken in Room 101 — when he begs for Julia to be tortured in his place — the last pretence of sacrifice is withdrawn, and his destruction is complete. The closing words, "He loved Big Brother," confirm that the rebel's sacrifice has not merely failed to generate collective change; it has been inverted into its opposite, converting resistance into love of the system that destroyed it. Orwell's argument is precise and devastating: individual sacrifice without the conditions for collective consequence is not heroism but tragedy.""",
b2_label='The Rebel Who Becomes a Symbol: V and the Transmissibility of Sacrifice',
body2="""V for Vendetta substantially challenges Orwell's conclusion by constructing a rebel whose individual sacrifice is specifically designed to generate collective consequence — and who understands, from the outset, that his own death is the precondition for the movement's success rather than its end. The crucial difference between V and Winston is not courage — both possess it — but strategic intelligence. V understands that personal survival is incompatible with the scale of change he intends: he tells Evey that he, like God, does not play with dice, and the entire final act of the film — the delivery of masks, the arrangement of the train, the systematic exposure of the regime's crimes — is the work of someone who has accepted their own expendability in order to maximise their impact beyond their own life. McTeigue reinforces this through the domino sequence: V painstakingly arranges thousands of tiles in the shape of the letter V and sets them falling, an extended visual metaphor for a plan whose consequences, once initiated, cascade beyond any individual's control. V's willingness to absorb Creedy's bullets while delivering the declaration that "ideas are bulletproof" is not merely brave but ideologically precise: by making his death part of the spectacle, V ensures that the act is witnessed, recorded, and transmitted — that it enters the population's consciousness as the image of an idea that could not be killed. The film's climax enacts the consequence of this design: V's individual sacrifice catalyses the collective act that determines the film's outcome. Evey activates the train; the crowd dons the masks; the soldier lowers his gun; Parliament falls. Each of these is a separate individual choice made by a different person — and each traces directly back to V's sacrifice. To the extent that individual sacrifice generates collective change, McTeigue argues, it depends on whether the rebel has created something transmissible: not a memory of a person but an idea that others can carry.""",
conclusion="""To the extent that both texts use the rebel figure to explore the relationship between individual sacrifice and collective change, they are ultimately asking the same question through different answers: what must be true of a sacrifice for it to matter beyond the person who makes it? Orwell's answer is bleak — under a sufficiently total system, nothing the individual can do is sufficient to generate consequences, because the system has been designed to absorb and nullify individual acts. McTeigue's answer is conditional but hopeful — individual sacrifice generates collective change when the rebel has understood that survival is not the goal, that the goal is the creation of a symbol or an idea robust enough to live without them. Together, the texts argue that the rebel's most important decision is not whether to resist, but how to ensure that the resistance endures."""
),

]

# ═════════════════════════════════════════════════════════════════════════════
# BUILD DOCUMENT
# ═════════════════════════════════════════════════════════════════════════════

# Cover page
add_cover_title('Eleven Model Comparative Essays')
add_subtitle('Nineteen Eighty-Four (Orwell, 1949) | V for Vendetta (McTeigue, 2005)')
add_subtitle('Essays 1–6: Thematic   |   Essays 7–11: "To What Extent"')
doc.add_paragraph()
add_subtitle('Each essay ~1,000–1,200 words. Follow your class body paragraph structure throughout.')

for e in essays:
    color = e['color']
    add_essay_heading(e['n'], f"{e['theme']} — {e['title']}", color=color)
    add_question_box(e['question'])

    add_section_label('Introduction', color)
    add_body(e['intro'])

    add_section_label(e['b1_label'], color)
    add_body(e['body1'])

    add_section_label(e['b2_label'], color)
    add_body(e['body2'])

    add_section_label('Conclusion', color)
    add_body(e['conclusion'])

    add_divider()

doc.save('eleven_model_essays.docx')
print('Done — eleven_model_essays.docx saved.')
